# Render Blueprint
version: 1
services:
  - type: web
    name: user_api
    env: docker
    docker:
      build:
        context: .
        # target: production # Si usas un multi-stage build
    ports:
      - "80:80"  # Cambia el puerto según sea necesario
    envVars:
      - key: SERVER_PORT
        value: ${SERVER_PORT}
      - key: PGHOST
        value: postgres-db  # El nombre del servicio de la base de datos
      - key: PGDATABASE
        value: ${PGDATABASE}
      - key: PGUSER
        value: ${PGUSER}
      - key: PGPASSWORD
        value: ${PGPASSWORD}
      - key: JWT_SECRET_SECRET
        value: ${JWT_SECRET_SECRET}
      - key: JWT_SECRET_HEADER
        value: ${JWT_SECRET_HEADER}
      - key: JWT_SECRET_HEADERS
        value: ${JWT_SECRET_HEADERS}
      - key: JWT_SECRET_EXPIRES
        value: ${JWT_SECRET_EXPIRES}
      - key: JWT_SECRET_REFRESH
        value: ${JWT_SECRET_REFRESH}
    # Render automáticamente maneja el link entre servicios, no es necesario usar depends_on o networks

  - type: postgres
    name: postgres-db
    version: 14
    # Render maneja automáticamente el almacenamiento persistente para bases de datos

# Opcional: Para definir secretos o variables de entorno globales
# secrets:
#   - key: PGPASSWORD
#     value: your_pg_password
#   - key: JWT_SECRET_SECRET
#     value: your_jwt_secret_secret
  # Agrega otros secretos aquí si es necesario
